In [4]:
import array as arr

In [5]:
a = arr.array('i', [1, 2, 3])

In [6]:
import numpy as np
import random

In [7]:
np.arange(25).reshape((5, 5))         # create a 1-d range and reshape
np.array(range(25)).reshape((5, 5))   # pass a Python range and reshape
np.array([5] * 25).reshape((5, 5))    # pass a Python list and reshape
np.empty((5, 5))                      # allocate, but don't initialize
np.ones((5, 5))                       # initialize with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
a = np.zeros(100)
print(a.size)

100


In [9]:
i=0
n = a.size
for i in range(100):
    a[i] = i+1
    i = i+1

In [10]:
print(a[99])

100.0


In [11]:
#list(range(1,101))

In [12]:
a = np.zeros((10,10))

In [13]:
for i in range(10):
    for j in range(10):
        if(i==j):
            a[i][j] = 5
        else:
            a[i][j] = -3

In [14]:
b =  10 + 10*np.random.rand(5,3)

In [15]:
b

array([[10.36156833, 19.53320285, 16.9024661 ],
       [11.7840834 , 14.59124543, 15.12918671],
       [16.18230946, 13.57788836, 19.29930913],
       [13.62258268, 19.89369151, 13.48046577],
       [17.9413399 , 16.13122308, 16.09359349]])

In [16]:
e = np.zeros((20))

In [17]:
i = 0
for i in range(20):
    if(i<=15):
        e[i] =  2 + random.random()
    else:
        e[i] = -2 + random.random()

In [18]:
e

array([ 2.22000918,  2.95697326,  2.07770888,  2.43446201,  2.89361337,
        2.09140615,  2.03650455,  2.70256433,  2.75259741,  2.42897582,
        2.01135926,  2.20048238,  2.83356788,  2.32832762,  2.90196823,
        2.98116227, -1.12196961, -1.36874402, -1.33207468, -1.14012988])